// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:82d8ae8d-1dae-45e3-9b3d-d78cc4caf9ed",
    "aws_cognito_region": "eu-central-1",
    "aws_mobile_analytics_app_id": "806330d65cf94f6ba7727fbc4cd66e4a",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_content_delivery_bucket": "ammarssistant-hostingbucket",
    "aws_content_delivery_bucket_region": "eu-central-1",
    "aws_content_delivery_url": "http://ammarssistant-hostingbucket.s3-website.eu-central-1.amazonaws.com"
};


export default awsmobile;
